Memoryviews are fickle
This raised a

BufferError: Existing exports of data: object cannot be re-sized

exception. I couldn't find the memoryview reference that causes this
(FWIW it sometimes happens when you transfer a user property)
so let's just use the alternate solution.